### ISSUE TITLE
image data 

### ISSUE THREAD

**Issue by puneetvaza** [ssudholt/phocnet#1]
can you provide me the image data

**Comment by ssudholt** [comment]
The image data is copyrighted which is why I can't upload it here. The locations are:

- George Washington: http://ciir.cs.umass.edu/downloads/old/data_sets.html
- IAM-DB: http://www.fki.inf.unibe.ch/databases/iam-handwriting-database
- Esposalles: http://dag.cvc.uab.es/the-esposalles-database/
- IFN/ENIT: http://www.ifnenit.com/
